### ISSUE TITLE
Criar ambiente local de desenvolvimento com base no tema deste repo

### ISSUE THREAD

**Issue by intrepidocabral** [lafabbricabr/geracaomais-wp-theme#1]
1. opção de ferramenta para criação do enviroment: http://vccw.cc
2. depois de criar o enviroment, instalar o tema dando git clone na pasta themes e ativando no painel
3. instale os plugins requeridos (são vários)
4. vá em 'aparencia' > 'theme demo data' e rode o seed para ele popular a base

Enviroment de homolog: http://dev.geracaomais.com.br

@vitor-kato avise aqui quando estiver done o seu enviroment

**Comment by photonauta35** [comment]
@vitor-kato avise aqui quando estiver done o seu enviroment

**Comment by vitor-kato** [comment]
- [x] Done!
